//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appHeroeMVC.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heroe
    {
        public int IdHeroe { get; set; }
        public string Nombre { get; set; }
        public string Historia { get; set; }
        public string Poder { get; set; }
        public string Debilidad { get; set; }
        public string Universo { get; set; }
        public string Imagen { get; set; }
    }
}
